apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-10
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/disk-space/pv-10
