
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mattermost
  name: mattermost
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8065
      targetPort: 8065
      protocol: TCP
  selector:
    app: mattermost
