
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      name: mattermost-pv
