
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-pv
  labels:
    name: mattermost-pv
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.13.3
    path: /root/matter
