
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  selector:
    matchLabels:
      name: mattermost-config-pv
