apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-002
  labels:
    app: wordpress
spec:
  ports:
    - port: 3307
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-002
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql-002
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: hypriot/rpi-mysql 
        name: mysql-02
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3307
          name: mysql-02
        volumeMounts:
        - name: mysql-persistent-storage-002
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-002
        persistentVolumeClaim:
          claimName: mysql-pv-claim-002
