apiVersion: v1
kind: Service
metadata:
  name: wordpress-002
  labels:
    app: wordpress-02
#spec:
#  ports:
#    - port: 80  
#  selector:
#    app: wordpress-02
#    tier: frontend
#  type: LoadBalancer
#  ports:
#    - name: "http-port"
#      protocol: "TCP"
#      port: 8080
#      targetPort: 80
#      nodePort: 30088 
#  ports:
#    - port: 31008
spec:
  ports:
  - port: 80
    nodePort: 31008
    targetPort: http-port
    protocol: TCP
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-002
  labels:
    app: wordpress-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpres-002
  labels:
    app: wordpress-02
spec:
  selector:
    matchLabels:
      app: wordpress-02
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-02
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpres-002
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpres-02
        volumeMounts:
        - name: wordpress-persistent-storage-002 
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage-002
        persistentVolumeClaim:
          claimName: wp-pv-claim-002
