apiVersion: v1
kind: Pod
metadata:
  labels:
    app: omgwtfssl
  name: omgwtfssl
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: SSL_SUBJECT
      value: rasp-master
    - name: CA_SUBJECT
      value: digihide@gmail.com
    - name: SSL_KEY
      value: /certs/rasp-master.key
    - name: SSL_CSR
      value: /certs/rasp-master.csr
    - name: SSL_CERT
      value: /certs/rasp-master.crt
    name: omgwtfssl
    image: paulczar/omgwtfssl
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: certs
      name: certs
  volumes:
    - name: certs
      hostPath:
        path: "/home/pi/certs-pv"
